### ISSUE TITLE
Nice Idea (non-issue)

### ISSUE THREAD

**Issue by AbeFM** [domesticatedviking/skinnydip#1]
I like this! Unfortunately my MMU is down for a week, but when I get it working again, I'm tempted to play with this.

In the past I tried manually editing my files to give me variable length cooling moves - trying to do the same thing but much less involved.

I'm looking forward to testing it!

**Comment by domesticatedviking** [comment]
Thanks for the feedback!  Good luck with it.   It has been working great for me in combination with an experimental torlon heatsink insert developed by David Shealey.   I've had to squash a bug or two along the way but nothing too serious.
