### ISSUE TITLE
--k option should only require one dash

### ISSUE THREAD

**Issue by PxT** [domesticatedviking/skinnydip#7]
Typically the short version "-k" of an option would only require one dash while the long one "--keep" would use two.  According to the help the script is expecting two dashes for the short argument:

```
$ ~/scripts/skinnydip.py -h
Skinnydip MMU2 String Eliminator v1.0.3 beta
usage: skinnydip.py [-h] [--k] myFile [myFile ...]

positional arguments:
  myFile

optional arguments:
  -h, --help   show this help message and exit
  --k, --keep  keep copy of original file
```

**Comment by domesticatedviking** [comment]
Thanks for this as well.  I wasn't aware of this convention, but I can see that I wasn't being consistent either. This will be fixed in the next release.
